import { Router, type IRouter } from "express";
import healthRouter from "./health";
import receiptScanRouter from "./receipt-scan";
import statementScanRouter from "./statement-scan";
import voiceParseRouter from "./voice-parse";
import broadcastEvalRouter from "./broadcast-eval";
import backupRouter from "./backup";
import documentsRouter from "./documents";
import gitPushRouter from "./git-push";
import geminiChatRouter from "./gemini-chat";
import limosysEvalRouter from "./limosys-eval";
import tripsRouter from "./trips";
import meRouter from "./me";
import claimLegacyBackupsRouter from "./claim-legacy-backups";
import geocodeRouter from "./geocode";
import expensesRouter from "./expenses";
import hoursRouter from "./hours";
import goalsRouter from "./goals";

const router: IRouter = Router();

router.use(healthRouter);
router.use(receiptScanRouter);
router.use(statementScanRouter);
router.use(voiceParseRouter);
router.use(broadcastEvalRouter);
router.use(backupRouter);
router.use(documentsRouter);
router.use(gitPushRouter);
router.use(geminiChatRouter);
router.use(limosysEvalRouter);
router.use(tripsRouter);
router.use(meRouter);
router.use(claimLegacyBackupsRouter);
router.use(geocodeRouter);
router.use(expensesRouter);
router.use(hoursRouter);
router.use(goalsRouter);

export default router;
