// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/islandcity/BankReconcile.tsx": () => import("../components/mockups/islandcity/BankReconcile.tsx"),
  "./components/mockups/islandcity/BankReconcileSwipe.tsx": () => import("../components/mockups/islandcity/BankReconcileSwipe.tsx"),
  "./components/mockups/islandcity/CashFlow.tsx": () => import("../components/mockups/islandcity/CashFlow.tsx"),
  "./components/mockups/islandcity/CashFlow3DTimeline.tsx": () => import("../components/mockups/islandcity/CashFlow3DTimeline.tsx"),
  "./components/mockups/islandcity/CashFlowBento.tsx": () => import("../components/mockups/islandcity/CashFlowBento.tsx"),
  "./components/mockups/islandcity/CashFlowBold.tsx": () => import("../components/mockups/islandcity/CashFlowBold.tsx"),
  "./components/mockups/islandcity/CashFlowJournal.tsx": () => import("../components/mockups/islandcity/CashFlowJournal.tsx"),
  "./components/mockups/islandcity/CashFlowRunway.tsx": () => import("../components/mockups/islandcity/CashFlowRunway.tsx"),
  "./components/mockups/islandcity/CashFlowRunwayAltLayout.tsx": () => import("../components/mockups/islandcity/CashFlowRunwayAltLayout.tsx"),
  "./components/mockups/islandcity/ExpenseProjection.tsx": () => import("../components/mockups/islandcity/ExpenseProjection.tsx"),
  "./components/mockups/islandcity/FinancesBold.tsx": () => import("../components/mockups/islandcity/FinancesBold.tsx"),
  "./components/mockups/islandcity/FinancesBoldChat.tsx": () => import("../components/mockups/islandcity/FinancesBoldChat.tsx"),
  "./components/mockups/islandcity/FinancesBoldNetBalance.tsx": () => import("../components/mockups/islandcity/FinancesBoldNetBalance.tsx"),
  "./components/mockups/islandcity/IncomeProjection.tsx": () => import("../components/mockups/islandcity/IncomeProjection.tsx"),
  "./components/mockups/islandcity/MonthlyPNL.tsx": () => import("../components/mockups/islandcity/MonthlyPNL.tsx"),
  "./components/mockups/islandcity/PushNotifications.tsx": () => import("../components/mockups/islandcity/PushNotifications.tsx"),
  "./components/mockups/islandcity/ReceiptScanner.tsx": () => import("../components/mockups/islandcity/ReceiptScanner.tsx"),
  "./components/mockups/islandcity/Speedometer.tsx": () => import("../components/mockups/islandcity/Speedometer.tsx"),
  "./components/mockups/trip-entry/QuickStrike.tsx": () => import("../components/mockups/trip-entry/QuickStrike.tsx"),
  "./components/mockups/trip-entry/SpeedDial.tsx": () => import("../components/mockups/trip-entry/SpeedDial.tsx"),
  "./components/mockups/theme-compare/DarkMode.tsx": () => import("../components/mockups/theme-compare/DarkMode.tsx"),
  "./components/mockups/theme-compare/LightMode.tsx": () => import("../components/mockups/theme-compare/LightMode.tsx"),
  "./components/mockups/theme-compare/ThemeSwitch.tsx": () => import("../components/mockups/theme-compare/ThemeSwitch.tsx")
};
